### ISSUE TITLE
Add screen to select game

### ISSUE THREAD

**Issue by hmumm** [hmumm/chip8emulator#13]
Add a screen before game loads to select a screen.

**Comment by MatheusMuriel** [comment]
Wow! This looks fine. 
How i configure the dev envioment?

**Comment by hmumm** [comment]
On Windows simply open the solution in visual studio 2019. I'm not sure how to do it on Linux or Mac but it's a .net core app so I'd assume you could use vscode.

**Comment by dlawin** [comment]
@hmumm did you have something in mind? I could do a simple form to select the .c8 file to use

Also is it good practice to "dibs" things? Could I be assigned? Just don't want to take this on if Matheus already has

**Comment by hmumm** [comment]
@spac3mandan I have no particular preference how you implement it. My only requirement would be that it be cross platform compatible.

As for good practice about dibsing things, it is probably a good idea although there is no strict requirement. I should really create a contributing.md file to create some rules but for now I have none. I will assign it to you though.

@MatheusMuriel if you are interested in working on this I apologize, try and comment here before @spac3mandan gets too far along.

**Comment by hmumm** [comment]
@dlawin I am unassigning you from this since you haven't commented or made any commits in the last month.
