### ISSUE TITLE
Refactor Chip8 class

### ISSUE THREAD

**Issue by hmumm** [hmumm/chip8emulator#2]
Start using delegates instead of using a giant switch case statement. This will make the code much easier to read, as well as possibly quicker (that will require some testing to know for sure)

**Comment by uuksu** [comment]
I had an idea how this could be implemented.

- Make base class for Instruction. Make it abstract and make abstract method called Execute with signature that takes in CPU "insides" (Registers, program counter...) as parameters (maybe as one object that could be later expanded if needed. Name could be for example CPUState). Make Execute return list of StateChange objects that contain information how the CPU state has changed. Make Instruction class also have public member "OpCode".
- Implement class for every instruction using the Instruction class as base class. Implement Execute by copying code from current switch case and return correct CPU state back. Make OpCode property return correct code.
- In Chip8, in startup use reflection to search all classes derived from Instruction base class and make dictionary of OpCode per class name. This will be used as look up table.
- When emulating cycle, read OpCode from Memory, find correct class from lookup dictionary, create instance of the object and execute Execute method. Use return value to change the CPU state.

This could be later use to make nice things like having backward debug stepping (CPU state can be stored when executing so we can also step backwards) and "human readable execution" (Instruction can create a description of what it is doing, for example: "Storing value XX to memory addres YY".

This is just one idea and I might have no thought every pithole with this one. Use it if you like it :)

**Comment by hmumm** [comment]
@uuksu I like your ideas here, I drew up some plans in draw.io what do you think of this so far? The CPUStateChange object is what I'm a little confused how that would be laid out. Would we have a copy of all the memory and everything in there similar to CPUState or how would that work exactly. 
![Chip8Refactoring](https://user-images.githubusercontent.com/28241556/95136913-a6017180-072c-11eb-9e4c-954ef785eb67.jpg)

Let me know what you think.

**Comment by uuksu** [comment]
I like it that you actually drew something, good job! Here are my comments about every box:

**BaseInstruction**

- Name could be just Instruction, Base is good to use sometimes when it's not so clean from OOP perspective what class is base class but now we clearly know that all classes derived from it are Instructions.

**CPUState**

- Why CPUState has the getOpCode method? I see this could be method found in the BaseInstuction instead. CPUState is not that interested of the OpCode as from it's perspective it's only part of the memory.

**CPUStateChange**

- I see that I failed to completely explain the change part so no wonder that you're confused :) My idea was that the StateChange is yet again base class. Then you have a subclasses of that with names like MemoryChange, VideoMemoryChange, ProgramCounterChange etc. When returned from the Execute method these changes are applied to the current CPU state in Chip8 class. This would help giving a nice debugging/logging capabilities ("Memory address XX changed to YY", "Program Counter changed to ZZ").
- Other idea would be to just return back the CPUState with modifed values and apply that to the current CPU state, but if we would like to store the execution history then this should be copied in Execute and the copy should be returned.

**Comment by hmumm** [comment]
Awesome. The easiest approach for the StateChange is actually just not to have one at all, instead just copy the state modify and return that. I don't think this is the right way to do it though, if we want to have backwards stepping eventually. I think it would be better to return somehow just what was changed ie Memory address 0x1 was 2 now it's 3. The reason is if we wanted to store every instruction continuously we'd have store a copy of the state for every single instruction run, which seems wasteful. Not sure how that could be stored exactly though. I guess that's what I'm still confused about.

**Comment by hmumm** [comment]
![Chip8Refactoring(1)](https://user-images.githubusercontent.com/28241556/95525195-1ad8e380-0999-11eb-8562-a452c12b71ac.jpg)

I think this is going to be my final design, we will see when I start coding, hopefully sometime this weekend. Thanks for the input 😄

**Comment by hmumm** [comment]
![Chip8Refactoring(2)](https://user-images.githubusercontent.com/28241556/95540518-95fcc280-09b6-11eb-8f6d-e84bd5f0e22c.jpg)
actually I forgot generics were a thing, I think this makes more sense

**Comment by uuksu** [comment]
This looks good! If you get stuck or need to brainstorm this, feel free to ask!

**Comment by hmumm** [comment]
Ok thanks. I have been making slow but steady progress 😄
