### ISSUE TITLE
Get working on Linux

### ISSUE THREAD

**Issue by hmumm** [hmumm/chip8emulator#9]
The project should theoretically work on Linux, but I haven't had time to test it. If it doesn't work modify it to work.

**Comment by uuksu** [comment]
This seems to work fine. Tested with Manjaro Linux, compiled with dotnet SDK 3.1.107.

I suggest removing the absolute path to your download directory from Game1.Initialize :)

**Comment by hmumm** [comment]
Ha ha yes I will add a screen to select a game at some point. Thanks.
